server:
  servlet:
    context-path: /
  port: ${SERVER_PORT:8000}

spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA:public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:5842}
    driverClassName: org.postgresql.Driver